# Generated by Django 3.0.5 on 2020-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='slug',
            field=models.CharField(default=' ', max_length=130),
            preserve_default=False,
        ),
    ]
